openapi: 3.0.1
info:
  version: "1.0.0"
  title: Open Banking Gateway Admin API (might be disabled)
  description: >-
    This API provides capability to manage bank configuration and protocol setup. It is enableable
    using 'admin.api.enabled' property.
externalDocs:
  url: "https://adorsys.github.com/open-banking-gateway"


paths:
  /v1/admin/banks:
    get:
      tags:
        - BankAdmin
      operationId: bankAdminGET
      summary: Listing of banks and their profiles and actions
      description: Cursor-paginated listing of banks and their profiles and actions
      responses:
        '200':
          $ref: "#/components/responses/200_BankProfileResult"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'

  /v1/admin/banks/{uuid}:
    get:
      tags:
        - BankAdmin
      operationId: bankAdminDetailsGET
      summary: Get bank actions and information using bank UUID
      description: Read bank profile configuration and related information
      responses:
        '200':
          $ref: "#/components/responses/200_BankProfileResult"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
    put:
      tags:
        - BankAdmin
      operationId: bankAdminDetailsPUT
      summary: Create new bank configuration (or replace entire existing)
      description: Create new bank configuration using assigned ID (UUID)
      responses:
        '200':
          $ref: "#/components/responses/200_BankProfileResult"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
    patch:
      tags:
        - BankAdmin
      operationId: bankAdminDetailsPATCH
      summary: Update part of bank configuration
      description: Update part of bank configuration (i.e. add new action like payment, or change API url)
      responses:
        '200':
          $ref: "#/components/responses/200_BankProfileResult"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
    delete:
      tags:
        - BankAdmin
      operationId: bankAdminDetailsDELETE
      summary: Delete bank and its configuration
      description: Delete banks and its configuration
      responses:
        '200':
          $ref: "#/components/responses/200_BankProfileResult"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'

components:
  headers: {}

  parameters: {}

  responses:

    200_BankProfileResult:
      description: Full bank profile
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/bankProfileResponse"

  schemas:
    # response DTOs
    bankProfileResponse:
      title: Bank Profile data Response
      type: object
      properties:
        bankDescriptor:
          type: array
          items:
            $ref: '#/components/schemas/bankDescriptor'
        keyword:
          type: String
          description: The bank search input string

    bankDescriptor:
      title: Bank Profile details
      type: object
      properties:
        keyword:
          type: String
          description: The bank search input string